apiVersion: apps/v1
kind: Deployment
metadata:
  name: bn-nodejs-cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bn-nodejs-cicd-demo
  template:
    metadata:
      labels:
        app: bn-nodejs-cicd-demo
    spec:
      containers:
        - name: bn-nodejs-cicd-demo
          image: 475309741409.dkr.ecr.ap-northeast-2.amazonaws.com/bn-nodejs-cicd-demo:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bn-nodejs-cicd-demo-svc
spec:
  type: LoadBalancer
  selector:
    app: bn-nodejs-cicd-demo
  ports:
    - port: 80
      targetPort: 3000
